<a href="https://colab.research.google.com/github/tharanivm/AIML-PREREQ-LEARNER/blob/main/Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#12-Jan-2026

In [ ]:
import numpy as np

# Create two matrices
matrix1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
matrix2 = np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]])

print("Matrix 1:\n", matrix1)
print("\nMatrix 2:\n", matrix2)



Matrix 1:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Matrix 2:
 [[9 8 7]
 [6 5 4]
 [3 2 1]]


In [ ]:
# Perform mathematical operations

# Addition
matrix_sum = matrix1 + matrix2
print("\nMatrix Sum (matrix1 + matrix2):\n", matrix_sum)

# Subtraction
matrix_difference = matrix1 - matrix2
print("\nMatrix Difference (matrix1 - matrix2):\n", matrix_difference)

# Element-wise multiplication
matrix_elementwise_product = matrix1 * matrix2
print("\nMatrix Element-wise Product (matrix1 * matrix2):\n", matrix_elementwise_product)

# Dot product (matrix multiplication)
matrix_dot_product = np.dot(matrix1, matrix2)
print("\nMatrix Dot Product (matrix1 @ matrix2):\n", matrix_dot_product)



Matrix Sum (matrix1 + matrix2):
 [[10 10 10]
 [10 10 10]
 [10 10 10]]

Matrix Difference (matrix1 - matrix2):
 [[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]

Matrix Element-wise Product (matrix1 * matrix2):
 [[ 9 16 21]
 [24 25 24]
 [21 16  9]]

Matrix Dot Product (matrix1 @ matrix2):
 [[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]


### Scalar Matrix
A scalar matrix is a diagonal matrix where all the diagonal elements are equal to a scalar value. It can be thought of as a scalar multiple of the identity matrix.

In [ ]:
import numpy as np

# Create a scalar matrix with scalar value 5
scalar_value = 5
identity_matrix = np.eye(3) # 3x3 identity matrix
scalar_matrix = scalar_value * identity_matrix

print("Scalar Value:", scalar_value)
print("Identity Matrix (3x3):\n", identity_matrix)
print("\nScalar Matrix (5 * Identity Matrix):\n", scalar_matrix)

Scalar Value: 5
Identity Matrix (3x3):
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Scalar Matrix (5 * Identity Matrix):
 [[5. 0. 0.]
 [0. 5. 0.]
 [0. 0. 5.]]


### Vector Matrix
In the context of matrices, a vector can be represented as a row matrix (1xN) or a column matrix (Nx1).

In [ ]:
import numpy as np

# Create a row vector
row_vector = np.array([[10, 20, 30]])
print("Row Vector (1x3):\n", row_vector)
print("Shape of Row Vector:", row_vector.shape)

# Create a column vector
column_vector = np.array([[40], [50], [60]])
print("\nColumn Vector (3x1):\n", column_vector)
print("Shape of Column Vector:", column_vector.shape)

# Another way to create a column vector from a 1D array
array_1d = np.array([70, 80, 90])
column_vector_from_1d = array_1d.reshape(-1, 1)
print("\nColumn Vector from 1D array (using reshape):\n", column_vector_from_1d)
print("Shape of Column Vector from 1D array:", column_vector_from_1d.shape)

Row Vector (1x3):
 [[10 20 30]]
Shape of Row Vector: (1, 3)

Column Vector (3x1):
 [[40]
 [50]
 [60]]
Shape of Column Vector: (3, 1)

Column Vector from 1D array (using reshape):
 [[70]
 [80]
 [90]]
Shape of Column Vector from 1D array: (3, 1)


### Transpose of a Matrix
The transpose of a matrix is an operator which flips a matrix over its diagonal; that is, it switches the row and column indices of the matrix by producing another matrix denoted by $A^T$ (or $A'$).

In [ ]:
import numpy as np

# Original matrix
original_matrix = np.array([[1, 2, 3], [4, 5, 6]])
print("Original Matrix (2x3):\n", original_matrix)

# Transpose using .T attribute
transposed_matrix_T = original_matrix.T
print("\nTransposed Matrix (using .T):\n", transposed_matrix_T)
print("Shape of Transposed Matrix (using .T):", transposed_matrix_T.shape)

# Transpose using np.transpose() function
transposed_matrix_func = np.transpose(original_matrix)
print("\nTransposed Matrix (using np.transpose()):\n", transposed_matrix_func)
print("Shape of Transposed Matrix (using np.transpose()):", transposed_matrix_func.shape)

# Transpose of a column vector becomes a row vector
column_vec = np.array([[10], [11], [12]])
print("\nOriginal Column Vector:\n", column_vec)
print("Transposed Column Vector:\n", column_vec.T)

Original Matrix (2x3):
 [[1 2 3]
 [4 5 6]]

Transposed Matrix (using .T):
 [[1 4]
 [2 5]
 [3 6]]
Shape of Transposed Matrix (using .T): (3, 2)

Transposed Matrix (using np.transpose()):
 [[1 4]
 [2 5]
 [3 6]]
Shape of Transposed Matrix (using np.transpose()): (3, 2)

Original Column Vector:
 [[10]
 [11]
 [12]]
Transposed Column Vector:
 [[10 11 12]]


In [ ]:
#13-Jan-2026